Разметка главной
htmlacademy-adaptive/1559249-pink-23 pull request #2
Opened 2021-07-23 14:30 UTC by alexandrtanana

2021-07-23 15:05 UTC, baileys-li requested changes
На удивление почти нет ошибок в БЭМе. Молодец!

2021-07-23 15:05 UTC, baileys-li commented on source/index.html
> +            <h2 class="text-desc">Устали от серости мегаполиса?<br>Нам есть, что вам
логичнее сделать элементом родительского блока `text__desc`

2021-07-23 15:05 UTC, baileys-li commented on source/index.html
> +            <p class="slider-review__subtitle">Это приложение перевернуло мой мир и позволило по-новому взглянуть на привычные серые вещи! А еще я познакомился со своей будущей женой в комментариях к
Цитату семантичнее обернуть в `blockquote`

Да и структуру можно поменять

2021-07-23 15:05 UTC, baileys-li commented on source/index.html
> +            <table class="table-slider__base">
Молодец что сразу сделал таблицу, но как же странно она выглядит. Почему всё заголовками?

2021-07-24 14:37 UTC, alexandrtanana commented on source/index.html
> +            <table class="table-slider__base">
Таблицу поменяю позже.

2021-07-25 06:12 UTC, merged